/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as DigitalMarketingIndexRouteImport } from './routes/digital-marketing.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingIndexRoute = DigitalMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DigitalMarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digital-marketing': typeof DigitalMarketingRouteWithChildren
  '/digital-marketing/': typeof DigitalMarketingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digital-marketing': typeof DigitalMarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digital-marketing': typeof DigitalMarketingRouteWithChildren
  '/digital-marketing/': typeof DigitalMarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/digital-marketing' | '/digital-marketing/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/digital-marketing'
  id: '__root__' | '/' | '/digital-marketing' | '/digital-marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalMarketingRoute: typeof DigitalMarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing/': {
      id: '/digital-marketing/'
      path: '/'
      fullPath: '/digital-marketing/'
      preLoaderRoute: typeof DigitalMarketingIndexRouteImport
      parentRoute: typeof DigitalMarketingRoute
    }
  }
}

interface DigitalMarketingRouteChildren {
  DigitalMarketingIndexRoute: typeof DigitalMarketingIndexRoute
}

const DigitalMarketingRouteChildren: DigitalMarketingRouteChildren = {
  DigitalMarketingIndexRoute: DigitalMarketingIndexRoute,
}

const DigitalMarketingRouteWithChildren =
  DigitalMarketingRoute._addFileChildren(DigitalMarketingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalMarketingRoute: DigitalMarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
