/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiImplementationRouteImport } from './routes/ai-implementation'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as DigitalMarketingIndexRouteImport } from './routes/digital-marketing.index'
import { Route as DigitalMarketingChannelMarketingRouteImport } from './routes/digital-marketing.channel-marketing'
import { Route as DigitalMarketingContentSearchRouteImport } from './routes/digital-marketing.content-search'
import { Route as DigitalMarketingWebsitesRouteImport } from './routes/digital-marketing.websites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImplementationRoute = AiImplementationRouteImport.update({
  id: '/ai-implementation',
  path: '/ai-implementation',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingIndexRoute = DigitalMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DigitalMarketingRoute,
} as any)
const DigitalMarketingChannelMarketingRoute =
  DigitalMarketingChannelMarketingRouteImport.update({
    id: '/channel-marketing',
    path: '/channel-marketing',
    getParentRoute: () => DigitalMarketingRoute,
  } as any)
const DigitalMarketingContentSearchRoute =
  DigitalMarketingContentSearchRouteImport.update({
    id: '/content-search',
    path: '/content-search',
    getParentRoute: () => DigitalMarketingRoute,
  } as any)
const DigitalMarketingWebsitesRoute =
  DigitalMarketingWebsitesRouteImport.update({
    id: '/websites',
    path: '/websites',
    getParentRoute: () => DigitalMarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-implementation': typeof AiImplementationRoute
  '/digital-marketing': typeof DigitalMarketingRouteWithChildren
  '/digital-marketing/channel-marketing': typeof DigitalMarketingChannelMarketingRoute
  '/digital-marketing/content-search': typeof DigitalMarketingContentSearchRoute
  '/digital-marketing/websites': typeof DigitalMarketingWebsitesRoute
  '/digital-marketing/': typeof DigitalMarketingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-implementation': typeof AiImplementationRoute
  '/digital-marketing/channel-marketing': typeof DigitalMarketingChannelMarketingRoute
  '/digital-marketing/content-search': typeof DigitalMarketingContentSearchRoute
  '/digital-marketing/websites': typeof DigitalMarketingWebsitesRoute
  '/digital-marketing': typeof DigitalMarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-implementation': typeof AiImplementationRoute
  '/digital-marketing': typeof DigitalMarketingRouteWithChildren
  '/digital-marketing/channel-marketing': typeof DigitalMarketingChannelMarketingRoute
  '/digital-marketing/content-search': typeof DigitalMarketingContentSearchRoute
  '/digital-marketing/websites': typeof DigitalMarketingWebsitesRoute
  '/digital-marketing/': typeof DigitalMarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-implementation'
    | '/digital-marketing'
    | '/digital-marketing/channel-marketing'
    | '/digital-marketing/content-search'
    | '/digital-marketing/websites'
    | '/digital-marketing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-implementation'
    | '/digital-marketing/channel-marketing'
    | '/digital-marketing/content-search'
    | '/digital-marketing/websites'
    | '/digital-marketing'
  id:
    | '__root__'
    | '/'
    | '/ai-implementation'
    | '/digital-marketing'
    | '/digital-marketing/channel-marketing'
    | '/digital-marketing/content-search'
    | '/digital-marketing/websites'
    | '/digital-marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiImplementationRoute: typeof AiImplementationRoute
  DigitalMarketingRoute: typeof DigitalMarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-implementation': {
      id: '/ai-implementation'
      path: '/ai-implementation'
      fullPath: '/ai-implementation'
      preLoaderRoute: typeof AiImplementationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing/': {
      id: '/digital-marketing/'
      path: '/'
      fullPath: '/digital-marketing/'
      preLoaderRoute: typeof DigitalMarketingIndexRouteImport
      parentRoute: typeof DigitalMarketingRoute
    }
    '/digital-marketing/channel-marketing': {
      id: '/digital-marketing/channel-marketing'
      path: '/channel-marketing'
      fullPath: '/digital-marketing/channel-marketing'
      preLoaderRoute: typeof DigitalMarketingChannelMarketingRouteImport
      parentRoute: typeof DigitalMarketingRoute
    }
    '/digital-marketing/content-search': {
      id: '/digital-marketing/content-search'
      path: '/content-search'
      fullPath: '/digital-marketing/content-search'
      preLoaderRoute: typeof DigitalMarketingContentSearchRouteImport
      parentRoute: typeof DigitalMarketingRoute
    }
    '/digital-marketing/websites': {
      id: '/digital-marketing/websites'
      path: '/websites'
      fullPath: '/digital-marketing/websites'
      preLoaderRoute: typeof DigitalMarketingWebsitesRouteImport
      parentRoute: typeof DigitalMarketingRoute
    }
  }
}

interface DigitalMarketingRouteChildren {
  DigitalMarketingChannelMarketingRoute: typeof DigitalMarketingChannelMarketingRoute
  DigitalMarketingContentSearchRoute: typeof DigitalMarketingContentSearchRoute
  DigitalMarketingWebsitesRoute: typeof DigitalMarketingWebsitesRoute
  DigitalMarketingIndexRoute: typeof DigitalMarketingIndexRoute
}

const DigitalMarketingRouteChildren: DigitalMarketingRouteChildren = {
  DigitalMarketingChannelMarketingRoute: DigitalMarketingChannelMarketingRoute,
  DigitalMarketingContentSearchRoute: DigitalMarketingContentSearchRoute,
  DigitalMarketingWebsitesRoute: DigitalMarketingWebsitesRoute,
  DigitalMarketingIndexRoute: DigitalMarketingIndexRoute,
}

const DigitalMarketingRouteWithChildren =
  DigitalMarketingRoute._addFileChildren(DigitalMarketingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiImplementationRoute: AiImplementationRoute,
  DigitalMarketingRoute: DigitalMarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
